"""re

Revision ID: 132df18d0c8a
Revises: 34856ba0c9f2
Create Date: 2013-11-01 06:37:23.822255
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic.
revision = '132df18d0c8a'
down_revision = '34856ba0c9f2'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', u'img_path')
    op.drop_column('videos', u'title')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column(u'title', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('videos', sa.Column(u'img_path', mysql.VARCHAR(length=120), nullable=True))
    ### end Alembic commands ###
