"""a

Revision ID: 179a0b7a2439
Revises: 52edd0e48c6e
Create Date: 2013-10-31 09:59:59.179063
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic.
revision = '179a0b7a2439'
down_revision = '52edd0e48c6e'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', u'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(u'email', mysql.VARCHAR(length=80), nullable=True))
    ### end Alembic commands ###
