"""a

Revision ID: 27aa306b89c5
Revises: 179a0b7a2439
Create Date: 2013-10-31 10:00:08.160840
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '27aa306b89c5'
down_revision = '179a0b7a2439'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    ### end Alembic commands ###
