"""up

Revision ID: 287b4fc7fe8c
Revises: 34441bbfbcb
Create Date: 2013-10-31 11:32:39.050344
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '287b4fc7fe8c'
down_revision = '34441bbfbcb'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
