"""up

Revision ID: 34441bbfbcb
Revises: 27aa306b89c5
Create Date: 2013-10-31 11:31:49.637763
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '34441bbfbcb'
down_revision = '27aa306b89c5'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
