"""a

Revision ID: 34856ba0c9f2
Revises: 57551c13a20d
Create Date: 2013-11-01 06:26:00.928129
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '34856ba0c9f2'
down_revision = '57551c13a20d'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
