"""up

Revision ID: 380e8def9f02
Revises: 287b4fc7fe8c
Create Date: 2013-10-31 11:33:07.011499
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '380e8def9f02'
down_revision = '287b4fc7fe8c'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
