"""up

Revision ID: 48838d603f57
Revises: 380e8def9f02
Create Date: 2013-10-31 11:33:46.279682
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '48838d603f57'
down_revision = '380e8def9f02'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
