"""re

Revision ID: 4f8d020132cb
Revises: 534f351a3913
Create Date: 2013-11-01 06:43:34.177456
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4f8d020132cb'
down_revision = '534f351a3913'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('title', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'title')
    ### end Alembic commands ###
