"""init

Revision ID: 52edd0e48c6e
Revises: c25fa5e6cd7
Create Date: 2013-10-31 09:57:59.162684
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '52edd0e48c6e'
down_revision = 'c25fa5e6cd7'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    ### end Alembic commands ###
