"""re

Revision ID: 534f351a3913
Revises: f3b5472547c
Create Date: 2013-11-01 06:43:17.972648
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic.
revision = '534f351a3913'
down_revision = 'f3b5472547c'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', u'title')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column(u'title', mysql.VARCHAR(length=30), nullable=True))
    ### end Alembic commands ###
