"""ffff

Revision ID: 57551c13a20d
Revises: 25fbe740ffa7
Create Date: 2013-10-31 11:41:40.895032
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '57551c13a20d'
down_revision = '25fbe740ffa7'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
