"""ffff

Revision ID: f3786481d2
Revises: 48838d603f57
Create Date: 2013-10-31 11:35:00.525623
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f3786481d2'
down_revision = '48838d603f57'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
