"""re

Revision ID: f3b5472547c
Revises: 132df18d0c8a
Create Date: 2013-11-01 06:37:33.389992
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f3b5472547c'
down_revision = '132df18d0c8a'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('title', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'title')
    ### end Alembic commands ###
